CREATE FUNCTION INITUNGET(amount int) RETURNS boolean
AS $$
BEGIN
    FOR i IN 1..amount LOOP
        INSERT INTO UNGET VALUES(i);
    END LOOP;
    RETURN TRUE;
END;
$$
LANGUAGE PLPGSQL;

CREATE FUNCTION UNINIT() RETURNS boolean
AS $$
BEGIN
    DROP TABLE UNGET CASCADE;
    DROP TABLE RAWCONTENT CASCADE;
    DROP TABLE CONTENT CASCADE;
    DROP FUNCTION INITUNGET(amount int);
    DROP FUNCTION UNINIT();
    RETURN TRUE;
END;
$$
LANGUAGE PLPGSQL;
